plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo VERSION=${nextRelease.version} > $GITHUB_ENV"
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
tagFormat: ${version}
branches:
  - "main"