name: Publish release files

on:
  push:
    tags:
      - "*"

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Run publish
        run: dotnet publish ./FPVNoiseDetector/FPVNoiseDetector.csproj /p:AssemblyVersion=${GITHUB_REF##*/} /p:UseAppHost=true --output .out_win --runtime win-x64 --self-contained false --verbosity quiet /p:PublishSingleFile=true --configuration Release --framework net7.0-windows
        # run: dotnet publish ./FPVNoiseDetector/FPVNoiseDetector.csproj /p:AssemblyVersion=${{ env.VERSION }} /p:UseAppHost=true --output .out_win --runtime win-x64 --self-contained false --verbosity quiet /p:PublishSingleFile=true --configuration Release --framework net7.0-windows

      - name: ZIP full app
        run: zip -r fpvnoise-${GITHUB_REF##*/}.zip .out_win/fpvnoise.exe .out_win/NoisePredictorModel.zip .out_win/tensorflow.dll .out_win/LICENSE.txt 

      - name: ZIP update
        run: zip -r fpvnoise-${GITHUB_REF##*/}-update.zip .out_win/fpvnoise.exe .out_win/LICENSE.txt 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fpvnoise-${GITHUB_REF##*/}
          path: fpvnoise-${GITHUB_REF##*/}.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fpvnoise-${GITHUB_REF##*/}-update
          path: fpvnoise-${GITHUB_REF##*/}-update.zip
